version: '3.7'

services:
  webserver:
    build: 
      context: ./webserver/wwwnew
      dockerfile: Dockerfile
    volumes:
      - ./webserver/wwwnew:/app
    ports:
      - 8081:8080
  wildfly:
    build: 
      context: ./IEA-Server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 9990:9990
  derby:
    image: az82/docker-derby:v1.3
    ports:
      - 1527:1527
