version: '3.7'

services:
  webserver:
    build: 
      context: ./webserver/wwwnew
      dockerfile: Dockerfile
    volumes:
      - ./webserver/wwwnew:/app
    ports:
      - 8081:8080
  quarkus:
    build: 
      context: ./iea
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080
  postgres:
    image: postgres
    restart: 'no'
    environment:
      - POSTGRES_PASSWORD=passme
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432